//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouTube_Downloader_DLL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YouTube_Downloader_DLL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;style type=&quot;&quot; text/css&quot;&quot;&gt;
        ///            body {{
        ///                border-left: 1px solid #DCDCDC;
        ///                border-right: 1px solid #DCDCDC;
        ///                border-top: 1px solid #DCDCDC;
        ///                border-bottom: 1px solid #DCDCDC;
        ///                font-family: RobotoDraft, &quot;&quot;Helvetica Neue&quot;&quot;, Helvetica, Arial;
        ///                font-size: 14px;
        ///            }}
        ///        &lt;/style&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///        {0}
        ///    &lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body {{
        ///				border-left: 1px solid #DCDCDC;
        ///				border-right: 1px solid #DCDCDC;
        ///				border-top: 1px solid #DCDCDC;
        ///				border-bottom: 1px solid #DCDCDC;
        ///				font-family: RobotoDraft, &quot;Helvetica Neue&quot;, Helvetica, Arial;
        ///				font-size: 14px;
        ///			}}
        ///
        ///			.container #content {{
        ///				padding: 5px;
        ///			}}
        ///
        ///			#content {{
        ///				position: relative;
        ///				top: 0;
        ///				left: 0;
        ///				bottom: 0;
        ///				right: 0;
        ///				overflow: auto;
        ///			}}
        ///
        ///			.info {{
        ///				height: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
    }
}
